### PR TITLE
Sc18

### PR DESCRIPTION
**Pull request by oksanaguba**
sc18 data to main repo

### CODE REVIEW

**Comment by ambrad** [comment]
Everything except the cmake mod is in perf-runs dir, right?

**Comment by ambrad** [comment]
What is the result of running `du -h --max-depth=1` on the perf-runs directory?

**Comment by oksanaguba** [comment]
5.9M	./sc18-results
5.9M	.

**Comment by oksanaguba** [comment]
... why not add a note to cmake file? it is just a comment -- i kept it locally for myself but i will forget about it one day.

**Comment by ambrad** [comment]
The note is fine. Just making sure that all other 841 files are in perf-runs. True?

**Comment by oksanaguba** [comment]
yes, there were 2 commits, 1 is a note to cmake file, another is new folder perf-runs with files in it.

**Comment by ambrad** [comment]
@bartgol what do you think of 5.9 MB of data going in the xx repo?

**Comment by ambrad** [comment]
Thanks @oksanaguba. Let's get input from Luca before merging. I'll wait to approve until then.

**Comment by bartgol** [comment]
It's not THAT much data, so I'm fine with it. Besides, now that we are porting the xx work in the e3sm repo, we will not be actively develop new stuff in the Hommexx repo anymore (probably).

**Comment by bartgol** [comment]
Argh, wrong button!

**Pull request merged**
