### PR TITLE
Changed tests names and their configuration

### PR DESCRIPTION
**Pull request by bartgol**
This PR does a couple of changes to the tests in hommexx.

1) the executable and tests root name is no longer prtcA or prtcB (impossible to pronounce, btw), but preqx-nlev26 and preqx-nlev72 (more verbose). These name roots are also applied to the tests.
2) the cmake logic used to configure tests namelists is extended to more options. So far we only used it to configure ne and ndays; now we use it also for rsplit, qsize, moisture and the name of vcoord files. This allows to have much fewer files in test/reg_test/namelists, increasing maintainability and lowering bugs (only 1 file to change for multiple tests).
3) Distinction between original fortran an kokkos versions (of executables, tests, and the likes) is now via a '-kokkos' appended to kokkos version. The fortran version has no hint (e.g., no '-f' appended to fortran tests names).

Note: we could push this evn further, and have a single namelist file, with plenty of cmake variables in it, so that we could use it also for tensorhv, nudiv, q6 and lim9 tests. However, those are more 'niche' options, not as often played around with as the others, so for those tests I put a specific namelist file.

### CODE REVIEW

**Comment by ambrad** [comment]
This is great. I'm doing a full run with baselines, etc.; I'll report back later this afternoon if all goes well.

**Comment by ambrad** [comment]
Everything worked for me.

Edit: No, wait, I'm seeing failures in the cxx_vs_f90 tests. Let me look into this.

**Review by ambrad — DISMISSED** [review]

**Comment by ambrad** [comment]
Looks like the diagnostics disagree.

**Comment by bartgol** [comment]
I'm on it.

**Review by ambrad — APPROVED** [review]
Confirmed to pass now.

**Pull request closed without merging**
